name: Notice to channel

on:
  schedule:
  - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  do:
    strategy:
      matrix:
        user_id: ["717028469992587315", "825979698425102346"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run a code
      run: python src/main.py
      env:
        TARGET_ID: ${{ matrix.user_id }}
        DISCORD_WEBHOOK_URI: ${{ secrets.DISCORD_WEBHOOK_URI }}
